name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: apt update
      run: sudo apt update
    - name: apt upgrade
      run: sudo apt upgrade
    - name: install
      run: sudo apt-get install -y libx11-dev xorg-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev
      
    - name: submodule
      run: git submodule update --init --recursive
    - name: compile glfw
      run: |
        cd 3rd_party/glfw
        cmake .
        make --build .
        
    - name: build examples
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build ..
