name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodule
      run: git submodule update --init --recursive
    - name: compile glfw
      run: |
        cd 3rd_party/glfw
        cmake .
        make
    - name: build examples
      run: |
        mkdir build
        cd build
        cmake -G Xcode ..
        cmake --build .
