name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: submodule
      run: git submodule update --init --recursive
    - name: compile glfw
      run: |
        cd 3rd_party/glfw
        cmake . -A x64
        cmake --build . --config Release
        ls
        
    - name: build examples
      run: |
        mkdir build
        cd build
        cmake -A x64 -DUSE_HEADERONLY=ON ..
        cmake --build . --config Release
