name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: submodule
      run: git submodule update --init --recursive
    - name: compile glfw
      run: |
        cd 3rd_party/glfw
        git clone https://github.com/doxygen/doxygen.git
        cd doxygen
        mkdir build
        cd build
        cmake -G "Unix Makefiles" ..
        make
        make install
        cd ../../
        cmake .
        make -f Makefile
        
    - name: build examples
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
