name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt update
    - name: apt upgrade
      run: sudo apt upgrade
    - name: install
      run: sudo apt-get install libglu1-mesa-dev mesa-common-dev freeglut3-dev
    - name: clone
      run: git clone https://github.com/goto-c/OpenGL.git
    - name: submodule
      run: git submodule update --init --recursive
    - name: cd->glfw
      run: cd 3rd_party/glfw
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: cd
      run: cd ../../
    - name: mkdir
      run: mkdir build
    - name: cd->build
      run: cd build
    - name: cmake
      run: cmake .
    - name: make
      run: make
