name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: install doxygen
      run: sudo apt-get install doxygen
    - name: submodule
      run: git submodule update --init --recursive
    - name: compile glfw
      run: |
        cd 3rd_party/glfw
        cmake .
        make
    - name: build examples
      run: |
        mkdir build
        cd build
        cmake ..
        make --build .
