name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodule
      run: git submodule update --init --recursive
    - name: mkdir
      run: mkdir build
    - name: cd
      run: cd build
    - name: cmake
      run: cmake -G Xcode ..
